[template]
cargo_generate_version = "0.23"
include = ["**/*.template", ".generate/**/*"]
ignore = [
    "target",
    "Cargo.lock",
    "*.sqlite3",
    "posts.db",
    "WIP.md",
    "key.pem",
    "cert.pem",
    "node_modules",
]

[placeholders.domain]
type = "string"
prompt = "Website domain for tunnel (empty -> skip tunnel setup)"
default = ""

[hooks]
post = ["post-generate.rhai"]